version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -t lib -r requirements.txt
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - echo "Add main.py file"
      - zip -g deployment_package.zip main.py
      - echo "Add router files"
      - zip -g deployment_package.zip ./routers/*
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name Slackbot-FastAPI-Lambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"