version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -t lib -r requirements.txt
  build:
    commands:
      - echo "Zipping deployment package..."
      - (cd lib; zip ../lambda_function.zip -r .)
      - zip lambda_function.zip -u main.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name Slackbot-FastAPI-Lambda --zip-file fileb://lambda_function.zip
      - echo "DONE!!"